package com.forensix.service;

import com.forensix.dao.AnomalyDAO;
import com.forensix.dao.EventDAO;
import com.forensix.dao.ScanDAO;
import com.forensix.model.Anomaly;
import com.forensix.model.AuditRecord;
import com.forensix.model.FileEvent;
import com.forensix.model.Scan;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Generates structured forensic audit reports from scan results and audit-chain state.
 */
public class ReportGenerator {
    private static final Logger LOGGER = Logger.getLogger(ReportGenerator.class.getName());

    private final ScanDAO scanDAO;
    private final EventDAO eventDAO;
    private final AnomalyDAO anomalyDAO;
    private final AuditService auditService;
    private final String reportsDir;

    public ReportGenerator(ScanDAO scanDAO, EventDAO eventDAO, AnomalyDAO anomalyDAO,
                           AuditService auditService, String reportsDir) {
        this.scanDAO = scanDAO;
        this.eventDAO = eventDAO;
        this.anomalyDAO = anomalyDAO;
        this.auditService = auditService;
        this.reportsDir = (reportsDir != null && !reportsDir.isBlank()) ? reportsDir : "reports";
        ensureReportsDirExists();
    }

    private void ensureReportsDirExists() {
        try {
            Path dir = Paths.get(reportsDir);
            if (!Files.exists(dir)) {
                Files.createDirectories(dir);
            }
        } catch (IOException e) {
            LOGGER.log(Level.WARNING, "Failed to create reports directory: " + reportsDir, e);
        }
    }

    /**
     * Builds and exports a comprehensive forensic report for a given scan session.
     *
     * @param scanId scan session ID
     * @return Path to generated report file
     */
    public Path generateReport(long scanId) {
        Scan scan = scanDAO.findById(scanId);
        if (scan == null) {
            throw new IllegalArgumentException("Scan not found with id: " + scanId);
        }

        List<FileEvent> events = eventDAO.findByScanId(scanId);
        List<Anomaly> anomalies = anomalyDAO.findByScanId(scanId);
        VerificationResult chainResult = auditService != null ? auditService.verifyChain() : null;
        List<AuditRecord> trail = auditService != null ? auditService.getAuditTrail() : List.of();

        String reportContent = buildReportText(scan, events, anomalies, chainResult, trail);

        String timestampStr = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss").format(LocalDateTime.now());
        String fileName = String.format("scan-report-%d-%s.txt", scanId, timestampStr);
        Path reportPath = Paths.get(reportsDir, fileName);

        try {
            Files.writeString(reportPath, reportContent, StandardCharsets.UTF_8);
            LOGGER.info("Forensic report exported successfully to: " + reportPath.toAbsolutePath());
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, "Failed to write report file: " + reportPath, e);
            throw new RuntimeException("Report file write failure", e);
        }

        return reportPath;
    }

    /**
     * Constructs the report text without saving to disk (useful for GUI preview).
     */
    public String buildReportText(Scan scan, List<FileEvent> events, List<Anomaly> anomalies,
                                  VerificationResult chainResult, List<AuditRecord> trail) {
        StringBuilder sb = new StringBuilder();

        sb.append("================================================================================\n");
        sb.append("                  FORENSIX — FILE INTEGRITY & SECURITY AUDIT REPORT            \n");
        sb.append("================================================================================\n");
        sb.append(String.format("Scan ID            : %d\n", scan.getId()));
        sb.append(String.format("Status             : %s\n", scan.getStatus()));
        sb.append(String.format("Started At         : %s\n", scan.getStartedAt()));
        sb.append(String.format("Finished At        : %s\n", scan.getFinishedAt() != null ? scan.getFinishedAt() : "N/A"));
        sb.append(String.format("Monitored Target   : %s\n", scan.getScannedDirectory()));
        sb.append("Generated By       : FORENSIX DFIR Toolkit v1.0.0 (SHA-256 Verified)\n");
        sb.append("--------------------------------------------------------------------------------\n\n");

        // Executive Summary
        long added = events.stream().filter(e -> e.getEventType() == FileEvent.EventType.ADDED).count();
        long modified = events.stream().filter(e -> e.getEventType() == FileEvent.EventType.MODIFIED).count();
        long deleted = events.stream().filter(e -> e.getEventType() == FileEvent.EventType.DELETED).count();
        long unchanged = events.stream().filter(e -> e.getEventType() == FileEvent.EventType.UNCHANGED).count();
        long errors = events.stream().filter(e -> e.getEventType() == FileEvent.EventType.SCAN_ERROR).count();

        sb.append("1. EXECUTIVE SUMMARY\n");
        sb.append("--------------------\n");
        sb.append(String.format("  * Total Files Scanned       : %d\n", events.size()));
        sb.append(String.format("  * Unchanged Files           : %d\n", unchanged));
        sb.append(String.format("  * Modified Files            : %d\n", modified));
        sb.append(String.format("  * Newly Added Files         : %d\n", added));
        sb.append(String.format("  * Deleted Files             : %d\n", deleted));
        sb.append(String.format("  * File Scan Errors          : %d\n", errors));
        sb.append(String.format("  * Log Anomalies Detected    : %d\n\n", anomalies.size()));

        // File Integrity Section
        sb.append("2. FILE INTEGRITY MONITORING (FIM) FINDINGS\n");
        sb.append("-------------------------------------------\n");
        List<FileEvent> significantEvents = events.stream()
                .filter(e -> e.getEventType() != FileEvent.EventType.UNCHANGED)
                .toList();

        if (significantEvents.isEmpty()) {
            sb.append("  [CLEAN] No unauthorized additions, modifications, or deletions detected.\n\n");
        } else {
            sb.append(String.format("  %-12s | %-32s | %s\n", "EVENT TYPE", "RELATIVE PATH", "CRYPTOGRAPHIC HASH"));
            sb.append("  " + "-".repeat(76) + "\n");
            for (FileEvent e : significantEvents) {
                String hashDetail;
                if (e.getEventType() == FileEvent.EventType.MODIFIED) {
                    hashDetail = "Old: " + shortHash(e.getOldHash()) + " -> New: " + shortHash(e.getNewHash());
                } else if (e.getEventType() == FileEvent.EventType.ADDED) {
                    hashDetail = "SHA256: " + shortHash(e.getNewHash());
                } else if (e.getEventType() == FileEvent.EventType.DELETED) {
                    hashDetail = "Prev SHA256: " + shortHash(e.getOldHash());
                } else {
                    hashDetail = "Error: " + e.getErrorMessage();
                }
                sb.append(String.format("  %-12s | %-32s | %s\n", e.getEventType(), e.getPath(), hashDetail));
            }
            sb.append("\n");
        }

        // Log Anomaly Section
        sb.append("3. LOG ANALYSIS & ANOMALY DETECTION FINDINGS\n");
        sb.append("--------------------------------------------\n");
        if (anomalies.isEmpty()) {
            sb.append("  [CLEAN] No security anomalies detected across analyzed logs.\n\n");
        } else {
            sb.append(String.format("  %-10s | %-30s | %s\n", "SEVERITY", "RULE TRIGGERED", "SOURCE ENTRY"));
            sb.append("  " + "-".repeat(76) + "\n");
            for (Anomaly a : anomalies) {
                sb.append(String.format("  %-10s | %-30s | %s\n", a.getSeverity(), a.getRuleTriggered(), a.getLogEntry()));
            }
            sb.append("\n");
        }

        // Tamper-Evident Audit Chain Section
        sb.append("4. TAMPER-EVIDENT AUDIT TRAIL & CHAIN-OF-CUSTODY\n");
        sb.append("------------------------------------------------\n");
        if (chainResult != null) {
            sb.append("  * Chain Verification Status : ").append(chainResult.isValid() ? "[VERIFIED INTACT]" : "[TAMPERING DETECTED!]").append("\n");
            sb.append("  * Verification Details      : ").append(chainResult.getMessage()).append("\n");
            if (!chainResult.isValid()) {
                sb.append("  * Broken Record ID          : #").append(chainResult.getBrokenRecordId()).append("\n");
                sb.append("  * Failure Type              : ").append(chainResult.getBrokenField()).append("\n");
            }
        }
        sb.append("  * Total Audit Chain Records : ").append(trail.size()).append("\n");
        if (!trail.isEmpty()) {
            AuditRecord latest = trail.get(trail.size() - 1);
            sb.append("  * Latest Sealed Hash        : ").append(latest.getRecordHash()).append("\n");
        }
        sb.append("\n");

        sb.append("================================================================================\n");
        sb.append("End of FORENSIX Audit Report. Cryptographically sealed via SHA-256 hash chaining.\n");
        sb.append("================================================================================\n");

        return sb.toString();
    }

    private String shortHash(String hash) {
        if (hash == null) return "N/A";
        if (hash.length() > 16) {
            return hash.substring(0, 16) + "...";
        }
        return hash;
    }
}
